### ISSUE TITLE
ReferenceFrame not properly set through config.txt

### ISSUE THREAD

**Issue by pdudenas** [usnistgov/cyrsoxs#7]
Whether ReferenceFrame is set to 0 or 1 in the config.txt file, CyRSoXS  runs the default setting (0). This only affects command line usage. ReferenceFrame gets set properly through the pybind interface.

**Comment by KumarSaurabh1992** [comment]
Some changes have been pushed to the branch refFrameDebug in response to issue. The reference frame can be changed through config file with input specified as:

ReferenceFrameLab = True. This corresponds to rotating the electric field. This is changed to the default behavior

ReferenceFrameLab = False. This corresponds to rotating the director vector. This seems to be wrong in the sense that it voilates the negative anisotropy at high q (based on the discussion with Dean, Pete and Eliott). 


Additionally, while debugging it seems that Algorithm 1 was doing wrong rotation. I tried to verified it. @pdudenas , it will be great if you can run your beta tests with both algorithms (I hope the code is fast enough to verify it quickly) once again to verify that everything is intact before merging the branch refFrameDebug into main. 

A minor bug in numbering of the author is also fixed.

**Comment by pbeaucage** [comment]
Is there a reason to change the input name?

If we're following semantic versioning, a change in a core parameter name is a breaking change that requires bumping the major version.  It seems like we could just as easily keep it as the 0/1 variable ReferenceFrame and not have to bump to version 2.x family.

**Comment by KumarSaurabh1992** [comment]
OK. I can make the changes and push it.

**Comment by pbeaucage** [comment]
@martintb pointed out earlier today, when we were talking, that one can also implement a parameter change as a "shadow change"; i.e, keep the old parameter name, have it change the same thing under the hood as the new one, and warn that it's deprecated.  So it's really up to you.  As long as it accepts the old parameter name in addition to the new and the old one still functions, it's not a breaking change, my mistake.

**Comment by KumarSaurabh1992** [comment]
I have renamed the config to ReferenceFrame, in order to be consistent with Pybind too. Just to be be sure that we all are in same page

ReferenceFrame =1. This corresponds to rotating the electric field. This is changed to the **default** behavior

ReferenceFrame = 0. This corresponds to rotating the director vector. This seems to be wrong in the sense that it voilates the negative anisotropy at high q (based on the discussion with Dean, Pete and Eliott).

**Comment by pdudenas** [comment]
Verified that ReferenceFrame=1 (LAB) is now the default reference frame, and reference frame can be set through the config.txt now. Results are identical with CommunicationMinimizing (0) and MemoryMinimizing (1) Algorithms.
